### ISSUE TITLE
ImportError: No module named Foundation

### ISSUE THREAD

**Issue by snailrowen** [parente/pyttsx#37]
Hi Everybody, I have installed pyttsx but I can't get it to work. For some reason I need the module "Fondation" which I do not have. I'm using OS 10.10, and when I try to execute script using pyttsx functions I get the error below. I'm not sure what to do, any help would be greatly appreciated!

/Users/johanbjorck/.bashrc: line 1: p: command not found
Traceback (most recent call last):
  File "/Users/johanbjorck/Google Drive/Sublime/earsight/pyttsx_test.py", line 3, in <module>
    engine = pyttsx.init()
  File "/usr/local/lib/python2.7/site-packages/pyttsx/__init__.py", line 39, in init
    eng = Engine(driverName, debug)
  File "/usr/local/lib/python2.7/site-packages/pyttsx/engine.py", line 45, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/usr/local/lib/python2.7/site-packages/pyttsx/driver.py", line 64, in __init__
    self._module = __import__(name, globals(), locals(), [driverName])
  File "/usr/local/lib/python2.7/site-packages/pyttsx/drivers/nsss.py", line 18, in <module>
    from Foundation import *
ImportError: No module named Foundation
[Finished in 0.1s with exit code 1]
[shell_cmd: python -u "/Users/johanbjorck/Google Drive/Sublime/earsight/pyttsx_test.py"]
[dir: /Users/johanbjorck/Google Drive/Sublime/earsight]
[path: /usr/bin:/bin:/usr/sbin:/sbin]

**Comment by kaptainkommie** [comment]
Try installing the Foundation module? Perhaps this is it?https://pypi.python.org/pypi/Foundations/2.1.0

-------- Original message --------

**Comment by snailrowen** [comment]
Hmm it didn't work, the link you said was for "Foundations" but I'm missing "Foundation". Any other bets?

**Comment by kaptainkommie** [comment]
I don't run macosx so I'm making guesses. Have you looked at and tried this? 
http://stackoverflow.com/questions/3098932/importerror-no-module-named-foundation
The user added the directory in which foundation resides to the python path.

-------- Original message --------

**Comment by snailrowen** [comment]
Thanks a lot. I tried adding that to my python path, but it still didn't work. Is there any other approach, or should I simply find another program?

**Comment by blacksector** [comment]
Try taking a look here: [ImportError: No module named Foundation](http://stackoverflow.com/questions/1614648/importerror-no-module-named-foundation)

**Comment by cainesap** [comment]
@snailrowen Did you solve this?
I had the same problem, the 'Foundation' error message when using 'main' Python (2.7) on Mac OS X 10.11 and trying to import pyttsx. But having set up a virtual environment with the `--system-site-packages` flag, I get one step further: I can `import pyttsx` without complaint about Foundation. But then see the following traceback in trying to define engine:
>>> $ import pyttsx
>>> $ engine = pyttsx.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyttsx/__init__.py", line 39, in init
    eng = Engine(driverName, debug)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyttsx/engine.py", line 45, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyttsx/driver.py", line 66, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyttsx/drivers/nsss.py", line 24, in buildDriver
    return NSSpeechDriver.alloc().initWithProxy(proxy)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyttsx/drivers/nsss.py", line 28, in initWithProxy
    self = super(NSSpeechDriver, self).init()
AttributeError: 'super' object has no attribute 'init'

**Comment by foges** [comment]
I ended up having to install pyobjc from top of tree, but now I get this error:

```
>>> import pyttsx
>>> engine = pyttsx.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyttsx/__init__.py", line 39, in init
    eng = Engine(driverName, debug)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyttsx/engine.py", line 45, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyttsx/driver.py", line 64, in __init__
    self._module = __import__(name, globals(), locals(), [driverName])
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyttsx/drivers/nsss.py", line 26, in <module>
    class NSSpeechDriver(NSObject):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 3 arguments for <unbound selector setProperty of NSSpeechDriver at 0x1088f4f38>
```

Any ideas?

**Comment by ideasotw** [comment]
Hmm nothing on this topic seems to work. Does anyone know what is actually coursing this?
Thanks

**Comment by jhonnydv** [comment]
I am getting the following error. I am running this code on mac.
Traceback (most recent call last):
  File "driver_event.py", line 2, in <module>
    engine = pyttsx.init()
  File "/usr/local/lib/python2.7/site-packages/pyttsx/__init__.py", line 39, in init
    eng = Engine(driverName, debug)
  File "/usr/local/lib/python2.7/site-packages/pyttsx/engine.py", line 45, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/usr/local/lib/python2.7/site-packages/pyttsx/driver.py", line 64, in __init__
    self._module = __import__(name, globals(), locals(), [driverName])
  File "/usr/local/lib/python2.7/site-packages/pyttsx/drivers/nsss.py", line 26, in <module>
    class NSSpeechDriver(NSObject):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector _toVoice of NSSpeechDriver at 0x1105f4cc8>

**Comment by cynliu98** [comment]
I'm having the same error as anjandv

**Comment by Mwarukason** [comment]
I got same error too, so how.?

**Comment by Randy808** [comment]
I'm also getting the error. Does anyone know any known configuration of Python this library works with?

**Comment by bolin-hsu** [comment]
On OS X El Capitan version 10.11.3, I encountered this issue. I used the following workaround:
export PYTHONPATH="/System/Library/Frameworks/Python.framework//Versions/2.7/Extras/lib/python/PyObjC"

**Comment by JoshuaCalder** [comment]
Thanks @bolin-hsu ! Worked great for me. 
I had to first install Pyobc and then your workaround solved the issue.

**Comment by praveen-1** [comment]
@JoshCalder   That solution didn't work for me. Did you install anything else?

**Comment by k-ksharma** [comment]
@JoshuaCalder i was having the foundation error too on mac. I'm using Sierra OS. I resolved the foundation error by runnning it in a virtual environment and it works without any error. But in virtual environment, i'm unable to simulate function key. Installing PyObjc creates this error. Can anyone help me ?

**Comment by rishabhbhardwaj** [comment]
@sharma16aug I am using virtualenv in macOS Sierra. I installed PyObjc but still getting the below error.
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    speech_engine = pyttsx.init()
  File "/Users/r0b00ko/.virtualenvs/test-assistent/lib/python2.7/site-packages/pyttsx/__init__.py", line 39, in init
    eng = Engine(driverName, debug)
  File "/Users/r0b00ko/.virtualenvs/test-assistent/lib/python2.7/site-packages/pyttsx/engine.py", line 45, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/Users/r0b00ko/.virtualenvs/test-assistent/lib/python2.7/site-packages/pyttsx/driver.py", line 64, in __init__
    self._module = __import__(name, globals(), locals(), [driverName])
  File "/Users/r0b00ko/.virtualenvs/test-assistent/lib/python2.7/site-packages/pyttsx/drivers/nsss.py", line 18, in <module>
    from Foundation import *
ImportError: No module named Foundation
```

**Comment by k-ksharma** [comment]
@rishabhbhardwaj pyobjc might have some error with it. before installing pyobjc pyttsx was running fine. but now fro my poject i left this module and switched to mac default speakers. instead of using pyttsx you can use the inbuilt module to transform text into speech.

use this :

from os import system
system('say hello world)
system('say -v Alex hello world)

these work perfectly.

**Comment by jackpgao** [comment]
‘ImportError: No module named Foundation’

Still have the same problem.

**Comment by pkworlz** [comment]
need help, getting this error on my mac.

Traceback (most recent call last):
  File "texttospeach.py", line 2, in <module>
    engine = pyttsx.init()
  File "/usr/local/lib/python2.7/site-packages/pyttsx/__init__.py", line 39, in init
    eng = Engine(driverName, debug)
  File "/usr/local/lib/python2.7/site-packages/pyttsx/engine.py", line 45, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/usr/local/lib/python2.7/site-packages/pyttsx/driver.py", line 64, in __init__
    self._module = __import__(name, globals(), locals(), [driverName])
  File "/usr/local/lib/python2.7/site-packages/pyttsx/drivers/nsss.py", line 18, in <module>
    from Foundation import *
ImportError: No module named Foundation

**Comment by Datartic** [comment]
@cainesap I got an error regarding NSObject.To resolve this in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages.., replace pyttsx3 with my attached file or Any resolved pyttsx3 file from git hub(I have attached a link file)
https://github.com/nateshmbhat/pyttsx3 paste this pyttsx3 extracted file in the place of old..which solved for me.

**Comment by packeteer** [comment]
**pip install pyobjc**  <- solved it for me

**Comment by missmint27** [comment]
> On OS X El Capitan version 10.11.3, I encountered this issue. I used the following workaround:
> export PYTHONPATH="/System/Library/Frameworks/Python.framework//Versions/2.7/Extras/lib/python/PyObjC"

I just found that I am not installed pyobjc

**Comment by TheDarkEyezor** [comment]
I already installed pyobjc. Still doesn't work for me. I've tried everything on this thread. Has anyone found a solution?

**Comment by ravicont1998** [comment]
go to the location of site-packages

there you will have a folder named foundation.

do - >renaming

sudo mv foundation/ Foundation/

this worked for me
