### ISSUE TITLE
 No module named 'engine'

### ISSUE THREAD

**Issue by lucasjinreal** [parente/pyttsx#56]
```
Traceback (most recent call last):
  File "stests.py", line 35, in <module>
    import pyttsx
  File "/usr/local/lib/python3.6/site-packages/pyttsx/__init__.py", line 18, in <module>
    from engine import Engine
ModuleNotFoundError: No module named 'engine'
```

What is this error?

**Comment by vikanezrimaya** [comment]
Having the same error when using sukeesh/Jarvis, which uses pyttsx.

No clue how to fix it.

**Comment by dan-kimani** [comment]
Having the same error too. Anyone with a fix for it?

**Comment by spreadred** [comment]
Are these errors occurring on OS X only?

**Comment by isabek** [comment]
I got this error when I tried to use pyttsx with python3. Then I changed python to python2.7 and it started working. I think pyttsx's API doesn't support python3 yet.

**Comment by Andresnotch** [comment]
I got that error on python 3.6, is it because pyttsx doesn't support python 3?
`>>> import pyttsx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\pyttsx\__init__.py", line 18, in <module>
    from engine import Engine
ModuleNotFoundError: No module named 'engine'`

**Comment by isabek** [comment]
@Andresnotch I think yes, pyttsx doesn't support Python 3.

**Comment by Sujith59911111** [comment]
Guy try install pyttsx3(for python3.) instead of pyttsx(for python2.)

and try this
import pyttsx3
engine = pyttsx3.init()
engine.say("Hello World")
engine.runAndWait()

**Comment by jageshmaharjan** [comment]
@sujith59911 , yup it was with python 3.x. Thanks
@kaptainkommie , not only OS X also for all machine.

**Comment by RajSharma1** [comment]
@sujith59911 
This is the error now...!!

![image](https://user-images.githubusercontent.com/24774699/40652869-25507e94-6357-11e8-915a-1cfe3b91ffc5.png)

**Comment by LuizFelipe2mn** [comment]
For those who still have an error, try this:

Step 1 - Try use pyttsx3 instead pyttsx
Step 2 - Change (import pyttsx3) for (from pyttsx3 import *)

**Comment by warsi22** [comment]
> @sujith59911
> This is the error now...!!
> 
> ![image](https://user-images.githubusercontent.com/24774699/40652869-25507e94-6357-11e8-915a-1cfe3b91ffc5.png)

try

import pyttsx3 as pys
engine = pys.init()
engine.say("Hello World")
engine.runAndWait()

**Comment by kodevyas** [comment]
@nickqidev I see that you have not been maintaining this project for quite some time as this issue has already been fixed but has not been updated on python package. If you don't mind I would love to maintain it for you. I am a newbie in the open-source world and this will be a great place for me to start.
Thanks

**Comment by ChandrasekarPerumal** [comment]
Guys i have updated python, version 3.7.4.. I tried using pyttsx3 package but it still shows 
ModuleNotFoundError: Nomodule named 'engine'... Any one help me.. I got stucked here for so long..
OS: linux 
Jupyter Notebook

**Comment by spreadred** [comment]
@kodevyas Why would you want to maintain this project? It seems to have been superseded by an actively maintained project:  https://github.com/nateshmbhat/pyttsx3

**Comment by kodevyas** [comment]
@ChandrsekarPerumal You don't need to use pysttx3. This repository has been already updated for both python2 and python3. Instead of directly installing from python package manager use this GitHub repository to install the package: 
`pip install git+https://github.com/RapidwareTech/pyttsx.git`
For more reference on how to install a python package directly from GitHub visit :[https://stackoverflow.com/questions/15268953/how-to-install-python-package-from-github](url)

**Comment by spreadred** [comment]
@kodevyas Is there any reason _NOT_ to use pysttx3 over this project, which, you, yourself has said isn't maintained? The last commit here was almost 4 years ago.

**Comment by kodevyas** [comment]
@kaptainkommie With all due respect, pyttsx3 is the reason I want to maintain this project. I had used this particular repository in my university years a lot of times just to have fun with it. **pyttsx3** is the abuse of open source community. The pyttsx3 has been copied from this repository and the creator of pyttsx3 removed the License intentionally from the source just to mark it his own. He/She could have simply forked it or left the License there in the source and I won't have had any problem with it. He/She took someone else's hard work and publishing it as his own, and I have a problem with that.

**Comment by spreadred** [comment]
@kodevyas Wow. A very brief and manual comparison of source code does indeed make it look like pysttx3 is in violation of the license of this project. Have you brought this up with `nateshmbhat` ?

**Comment by spreadred** [comment]
@kodevyas Well this happened :) https://github.com/nateshmbhat/pyttsx3/issues/108

**Comment by programmingthegod** [comment]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\hp\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-bftoj3r8\\comtypes\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-bftoj3r8\\comtypes\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-9iotwlzi'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-bftoj3r8\comtypes\
    Complete output (26 lines):
    Traceback (most recent call last):
      File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2867, in get_entry_map
        ep_map = self._ep_map
      File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2825, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HP\AppData\Local\Temp\pip-install-bftoj3r8\comtypes\setup.py", line 173, in <module>
        dist = setup(**setup_params)
      File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 131, in _install_setup_requires
        dist = distutils.core.Distribution(dict(
      File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\dist.py", line 423, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 657, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2869, in get_entry_map
        ep_map = self._ep_map = EntryPoint.parse_map(
      File "c:\users\hp\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2541, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.



this is the new error.
please help in solving
